from io import BytesIO
from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


def build_patient_report_pdf(
    *,
    patient_name: str,
    hybrid_risk: str | None,
    last_hb: dict | None,
    out_path: Path,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    w, h = letter
    y = h - 50
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Dementia Guardian — Patient summary")
    y -= 36
    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"Patient: {patient_name}")
    y -= 22
    c.drawString(50, y, f"Hybrid risk (latest): {hybrid_risk or 'N/A'}")
    y -= 22
    if last_hb:
        lat = last_hb.get("latitude")
        lng = last_hb.get("longitude")
        ts = last_hb.get("createdAt")
        c.drawString(50, y, f"Last heartbeat: lat={lat}, lng={lng}, at={ts}")
        y -= 22
    else:
        c.drawString(50, y, "Last heartbeat: none on file")
        y -= 22
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 40, "Generated by Dementia Guardian API (Python)")
    c.showPage()
    c.save()
    out_path.write_bytes(buf.getvalue())
